//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Film_Day_Session = new HashSet<Film_Day_Session>();
            this.Session = new HashSet<Session>();
        }
    
        public int ID { get; set; }
        public int Saloon_ID { get; set; }
        public string Name { get; set; }
        public string Film_Genre { get; set; }
        public byte[] Poster { get; set; }
        public string Trailer { get; set; }
        public bool Status { get; set; }
        public System.DateTime First_Presentation { get; set; }
        public System.DateTime Last_Presentation { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Film_Day_Session> Film_Day_Session { get; set; }
        public virtual Saloon Saloon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }
    }
}
